### ISSUE TITLE
Publish in nixpkgs

### ISSUE THREAD

**Issue by masaeedu** [tazjin/nixfd#1]
It'd be pretty convenient if I could just do `nix-env -i nixfd` on new systems instead of installing rustup -> rust -> nixdf.

**Comment by tazjin** [comment]
Hey! 

That's a good point - I don't know what the policies for package inclusion are upstream (i.e. is this package too niche?). Will look into that.

In the meantime, I have a package in my Nix config: https://github.com/tazjin/nixos-config/blob/master/pkgs/nixfd.nix

**Comment by mkaito** [comment]
The upstream policy is pretty much: if someone finds it useful, it can go in nixpkgs. Please send them a PR.

**Comment by tazjin** [comment]
@mkaito I don't think it makes much sense at this point, NixOS 18.03 is about to drop with Nix 2.0 which includes this functionality in the default `nix` command :)

**Comment by mkaito** [comment]
Oh, I did not know that. Good to know!

**Comment by bbarker** [comment]
+1, `nix search` still seems to have bugs for some: https://github.com/NixOS/nix/issues/1892
